import { collection, doc, writeBatch, getDocs, query, where } from "firebase/firestore";
import { db } from "@/lib/backend/firebase/init";

/**
 * Service for importing shift type data
 */
export class ShiftTypeImportService {
    /**
     * Batch import shift type data
     */
    static async batchImportShiftTypes(
        shiftTypeData: Array<{
            timestamp: string;
            name: string;
            workingDays: Array<{
                dayOfTheWeek: string;
                associatedShiftHour: string;
            }>;
            startDate: string;
            endDate: string;
            active: "Yes" | "No";
        }>,
    ): Promise<{
        successful: number;
        failed: number;
        errors: string[];
    }> {
        const batch = writeBatch(db);
        const errors: string[] = [];
        let successful = 0;
        let failed = 0;

        try {
            // Check for duplicates and prepare batch operations
            for (const item of shiftTypeData) {
                try {
                    // Validate uniqueness - check if shift type name already exists
                    const existingQuery = query(
                        collection(db, "hrSettings"),
                        where("shiftTypes", "array-contains-any", [{ name: item.name }]),
                    );
                    const existingDocs = await getDocs(existingQuery);

                    // Check if any existing shift type has the same name
                    let nameExists = false;
                    existingDocs.forEach(doc => {
                        const data = doc.data();
                        if (data.shiftTypes) {
                            const hasMatchingName = data.shiftTypes.some(
                                (st: any) => st.name.toLowerCase() === item.name.toLowerCase(),
                            );
                            if (hasMatchingName) {
                                nameExists = true;
                            }
                        }
                    });

                    if (nameExists) {
                        failed++;
                        errors.push(`Shift type with name '${item.name}' already exists`);
                        continue;
                    }

                    // Get the hrSettings document
                    const hrSettingsQuery = query(collection(db, "hrSettings"));
                    const hrSettingsDocs = await getDocs(hrSettingsQuery);

                    if (hrSettingsDocs.empty) {
                        failed++;
                        errors.push("HR Settings document not found");
                        continue;
                    }

                    // Use the first hrSettings document
                    const hrSettingsDoc = hrSettingsDocs.docs[0];
                    const hrSettingsRef = doc(db, "hrSettings", hrSettingsDoc.id);

                    // Create the new shift type (ID will be generated by Firebase)
                    const newShiftType = item;

                    // Update the shiftTypes array by adding the new shift type
                    const currentShiftTypes = hrSettingsDoc.data().shiftTypes || [];
                    const updatedShiftTypes = [...currentShiftTypes, newShiftType];

                    batch.update(hrSettingsRef, {
                        shiftTypes: updatedShiftTypes,
                    });

                    successful++;
                } catch (error) {
                    failed++;
                    errors.push(
                        `Failed to process shift type ${item.name}: ${
                            error instanceof Error ? error.message : "Unknown error"
                        }`,
                    );
                }
            }

            // Commit batch
            await batch.commit();
        } catch (error) {
            console.error("Batch import error:", error);
            throw new Error(
                `Import failed: ${error instanceof Error ? error.message : "Unknown error"}`,
            );
        }

        return { successful, failed, errors };
    }

    /**
     * Validates shift type data before import
     */
    static validateShiftTypeData(shiftTypeData: any[]): {
        isValid: boolean;
        errors: string[];
    } {
        const errors: string[] = [];

        for (const item of shiftTypeData) {
            // Validate required fields
            if (!item.name || !item.name.trim()) {
                errors.push("Shift type name is required");
            }

            if (!item.startDate) {
                errors.push("Start date is required");
            }

            if (!item.endDate) {
                errors.push("End date is required");
            }

            if (!item.active) {
                errors.push("Active status is required");
            }

            if (!item.workingDays || !Array.isArray(item.workingDays)) {
                errors.push("Working days array is required");
            }

            // Validate date format
            if (item.startDate && item.endDate) {
                const startDate = new Date(item.startDate);
                const endDate = new Date(item.endDate);

                if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
                    errors.push("Invalid date format");
                } else if (startDate >= endDate) {
                    errors.push("Start date must be before end date");
                }
            }

            // Validate active status
            if (item.active && !["Yes", "No"].includes(item.active)) {
                errors.push("Active status must be 'Yes' or 'No'");
            }

            // Validate working days structure
            if (item.workingDays && Array.isArray(item.workingDays)) {
                for (const workingDay of item.workingDays) {
                    if (!workingDay.dayOfTheWeek) {
                        errors.push("Each working day must have a dayOfTheWeek");
                    }
                    if (!workingDay.associatedShiftHour) {
                        errors.push("Each working day must have an associatedShiftHour");
                    }
                }
            }
        }

        return {
            isValid: errors.length === 0,
            errors,
        };
    }
}
