export const countryCodes = [
    { code: "+93", country: "Afghanistan", flag: "🇦🇫", length: 9 },
    { code: "+355", country: "Albania", flag: "🇦🇱", length: 9 },
    { code: "+213", country: "Algeria", flag: "🇩🇿", length: 9 },
    { code: "+1", country: "United States", flag: "🇺🇸", length: 10 },
    { code: "+376", country: "Andorra", flag: "🇦🇩", length: 6 },
    { code: "+244", country: "Angola", flag: "🇦🇴", length: 9 },
    { code: "+54", country: "Argentina", flag: "🇦🇷", length: 10 },
    { code: "+374", country: "Armenia", flag: "🇦🇲", length: 8 },
    { code: "+61", country: "Australia", flag: "🇦🇺", length: 9 },
    { code: "+43", country: "Austria", flag: "🇦🇹", length: 10 },
    { code: "+994", country: "Azerbaijan", flag: "🇦🇿", length: 9 },
    { code: "+973", country: "Bahrain", flag: "🇧🇭", length: 8 },
    { code: "+880", country: "Bangladesh", flag: "🇧🇩", length: 10 },
    { code: "+375", country: "Belarus", flag: "🇧🇾", length: 9 },
    { code: "+32", country: "Belgium", flag: "🇧🇪", length: 9 },
    { code: "+501", country: "Belize", flag: "🇧🇿", length: 7 },
    { code: "+229", country: "Benin", flag: "🇧🇯", length: 8 },
    { code: "+975", country: "Bhutan", flag: "🇧🇹", length: 8 },
    { code: "+591", country: "Bolivia", flag: "🇧🇴", length: 8 },
    { code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦", length: 8 },
    { code: "+267", country: "Botswana", flag: "🇧🇼", length: 8 },
    { code: "+55", country: "Brazil", flag: "🇧🇷", length: 11 },
    { code: "+673", country: "Brunei", flag: "🇧🇳", length: 7 },
    { code: "+359", country: "Bulgaria", flag: "🇧🇬", length: 9 },
    { code: "+226", country: "Burkina Faso", flag: "🇧🇫", length: 8 },
    { code: "+257", country: "Burundi", flag: "🇧🇮", length: 8 },
    { code: "+855", country: "Cambodia", flag: "🇰🇭", length: 9 },
    { code: "+237", country: "Cameroon", flag: "🇨🇲", length: 9 },
    { code: "+1", country: "Canada", flag: "🇨🇦", length: 10 },
    { code: "+238", country: "Cape Verde", flag: "🇨🇻", length: 7 },
    { code: "+236", country: "Central African Republic", flag: "🇨🇫", length: 8 },
    { code: "+235", country: "Chad", flag: "🇹🇩", length: 8 },
    { code: "+56", country: "Chile", flag: "🇨🇱", length: 9 },
    { code: "+86", country: "China", flag: "🇨🇳", length: 11 },
    { code: "+57", country: "Colombia", flag: "🇨🇴", length: 10 },
    { code: "+269", country: "Comoros", flag: "🇰🇲", length: 7 },
    { code: "+242", country: "Congo", flag: "🇨🇬", length: 9 },
    { code: "+243", country: "Democratic Republic of Congo", flag: "🇨🇩", length: 9 },
    { code: "+506", country: "Costa Rica", flag: "🇨🇷", length: 8 },
    { code: "+385", country: "Croatia", flag: "🇭🇷", length: 9 },
    { code: "+53", country: "Cuba", flag: "🇨🇺", length: 8 },
    { code: "+357", country: "Cyprus", flag: "🇨🇾", length: 8 },
    { code: "+420", country: "Czech Republic", flag: "🇨🇿", length: 9 },
    { code: "+45", country: "Denmark", flag: "🇩🇰", length: 8 },
    { code: "+253", country: "Djibouti", flag: "🇩🇯", length: 8 },
    { code: "+593", country: "Ecuador", flag: "🇪🇨", length: 9 },
    { code: "+20", country: "Egypt", flag: "🇪🇬", length: 10 },
    { code: "+503", country: "El Salvador", flag: "🇸🇻", length: 8 },
    { code: "+240", country: "Equatorial Guinea", flag: "🇬🇶", length: 9 },
    { code: "+291", country: "Eritrea", flag: "🇪🇷", length: 7 },
    { code: "+372", country: "Estonia", flag: "🇪🇪", length: 8 },
    { code: "+251", country: "Ethiopia", flag: "🇪🇹", length: 9 },
    { code: "+358", country: "Finland", flag: "🇫🇮", length: 9 },
    { code: "+33", country: "France", flag: "🇫🇷", length: 10 },
    { code: "+241", country: "Gabon", flag: "🇬🇦", length: 8 },
    { code: "+220", country: "Gambia", flag: "🇬🇲", length: 7 },
    { code: "+995", country: "Georgia", flag: "🇬🇪", length: 9 },
    { code: "+49", country: "Germany", flag: "🇩🇪", length: 11 },
    { code: "+233", country: "Ghana", flag: "🇬🇭", length: 9 },
    { code: "+30", country: "Greece", flag: "🇬🇷", length: 10 },
    { code: "+502", country: "Guatemala", flag: "🇬🇹", length: 8 },
    { code: "+224", country: "Guinea", flag: "🇬🇳", length: 9 },
    { code: "+245", country: "Guinea-Bissau", flag: "🇬🇼", length: 7 },
    { code: "+592", country: "Guyana", flag: "🇬🇾", length: 7 },
    { code: "+509", country: "Haiti", flag: "🇭🇹", length: 8 },
    { code: "+504", country: "Honduras", flag: "🇭🇳", length: 8 },
    { code: "+36", country: "Hungary", flag: "🇭🇺", length: 9 },
    { code: "+354", country: "Iceland", flag: "🇮🇸", length: 7 },
    { code: "+91", country: "India", flag: "🇮🇳", length: 10 },
    { code: "+62", country: "Indonesia", flag: "🇮🇩", length: 10 },
    { code: "+98", country: "Iran", flag: "🇮🇷", length: 10 },
    { code: "+964", country: "Iraq", flag: "🇮🇶", length: 10 },
    { code: "+353", country: "Ireland", flag: "🇮🇪", length: 9 },
    { code: "+972", country: "Israel", flag: "🇮🇱", length: 9 },
    { code: "+39", country: "Italy", flag: "🇮🇹", length: 10 },
    { code: "+225", country: "Ivory Coast", flag: "🇨🇮", length: 8 },
    { code: "+81", country: "Japan", flag: "🇯🇵", length: 10 },
    { code: "+962", country: "Jordan", flag: "🇯🇴", length: 9 },
    { code: "+7", country: "Kazakhstan", flag: "🇰🇿", length: 10 },
    { code: "+254", country: "Kenya", flag: "🇰🇪", length: 9 },
    { code: "+965", country: "Kuwait", flag: "🇰🇼", length: 8 },
    { code: "+996", country: "Kyrgyzstan", flag: "🇰🇬", length: 9 },
    { code: "+856", country: "Laos", flag: "🇱🇦", length: 8 },
    { code: "+371", country: "Latvia", flag: "🇱🇻", length: 8 },
    { code: "+961", country: "Lebanon", flag: "🇱🇧", length: 8 },
    { code: "+266", country: "Lesotho", flag: "🇱🇸", length: 8 },
    { code: "+231", country: "Liberia", flag: "🇱🇷", length: 8 },
    { code: "+218", country: "Libya", flag: "🇱🇾", length: 9 },
    { code: "+370", country: "Lithuania", flag: "🇱🇹", length: 8 },
    { code: "+352", country: "Luxembourg", flag: "🇱🇺", length: 9 },
    { code: "+261", country: "Madagascar", flag: "🇲🇬", length: 9 },
    { code: "+265", country: "Malawi", flag: "🇲🇼", length: 9 },
    { code: "+60", country: "Malaysia", flag: "🇲🇾", length: 9 },
    { code: "+960", country: "Maldives", flag: "🇲🇻", length: 7 },
    { code: "+223", country: "Mali", flag: "🇲🇱", length: 8 },
    { code: "+356", country: "Malta", flag: "🇲🇹", length: 8 },
    { code: "+222", country: "Mauritania", flag: "🇲🇷", length: 8 },
    { code: "+230", country: "Mauritius", flag: "🇲🇺", length: 8 },
    { code: "+52", country: "Mexico", flag: "🇲🇽", length: 10 },
    { code: "+373", country: "Moldova", flag: "🇲🇩", length: 8 },
    { code: "+377", country: "Monaco", flag: "🇲🇨", length: 8 },
    { code: "+976", country: "Mongolia", flag: "🇲🇳", length: 8 },
    { code: "+382", country: "Montenegro", flag: "🇲🇪", length: 8 },
    { code: "+212", country: "Morocco", flag: "🇲🇦", length: 9 },
    { code: "+258", country: "Mozambique", flag: "🇲🇿", length: 9 },
    { code: "+95", country: "Myanmar", flag: "🇲🇲", length: 9 },
    { code: "+264", country: "Namibia", flag: "🇳🇦", length: 9 },
    { code: "+977", country: "Nepal", flag: "🇳🇵", length: 10 },
    { code: "+31", country: "Netherlands", flag: "🇳🇱", length: 9 },
    { code: "+64", country: "New Zealand", flag: "🇳🇿", length: 9 },
    { code: "+505", country: "Nicaragua", flag: "🇳🇮", length: 8 },
    { code: "+227", country: "Niger", flag: "🇳🇪", length: 8 },
    { code: "+234", country: "Nigeria", flag: "🇳🇬", length: 10 },
    { code: "+47", country: "Norway", flag: "🇳🇴", length: 8 },
    { code: "+968", country: "Oman", flag: "🇴🇲", length: 8 },
    { code: "+92", country: "Pakistan", flag: "🇵🇰", length: 10 },
    { code: "+507", country: "Panama", flag: "🇵🇦", length: 8 },
    { code: "+675", country: "Papua New Guinea", flag: "🇵🇬", length: 8 },
    { code: "+595", country: "Paraguay", flag: "🇵🇾", length: 9 },
    { code: "+51", country: "Peru", flag: "🇵🇪", length: 9 },
    { code: "+63", country: "Philippines", flag: "🇵🇭", length: 10 },
    { code: "+48", country: "Poland", flag: "🇵🇱", length: 9 },
    { code: "+351", country: "Portugal", flag: "🇵🇹", length: 9 },
    { code: "+974", country: "Qatar", flag: "🇶🇦", length: 8 },
    { code: "+40", country: "Romania", flag: "🇷🇴", length: 9 },
    { code: "+7", country: "Russia", flag: "🇷🇺", length: 10 },
    { code: "+250", country: "Rwanda", flag: "🇷🇼", length: 9 },
    { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", length: 9 },
    { code: "+221", country: "Senegal", flag: "🇸🇳", length: 9 },
    { code: "+381", country: "Serbia", flag: "🇷🇸", length: 9 },
    { code: "+248", country: "Seychelles", flag: "🇸🇨", length: 7 },
    { code: "+232", country: "Sierra Leone", flag: "🇸🇱", length: 8 },
    { code: "+65", country: "Singapore", flag: "🇸🇬", length: 8 },
    { code: "+421", country: "Slovakia", flag: "🇸🇰", length: 9 },
    { code: "+386", country: "Slovenia", flag: "🇸🇮", length: 8 },
    { code: "+252", country: "Somalia", flag: "🇸🇴", length: 8 },
    { code: "+27", country: "South Africa", flag: "🇿🇦", length: 9 },
    { code: "+82", country: "South Korea", flag: "🇰🇷", length: 10 },
    { code: "+211", country: "South Sudan", flag: "🇸🇸", length: 9 },
    { code: "+34", country: "Spain", flag: "🇪🇸", length: 9 },
    { code: "+94", country: "Sri Lanka", flag: "🇱🇰", length: 9 },
    { code: "+249", country: "Sudan", flag: "🇸🇩", length: 9 },
    { code: "+597", country: "Suriname", flag: "🇸🇷", length: 7 },
    { code: "+268", country: "Eswatini", flag: "🇸🇿", length: 8 },
    { code: "+46", country: "Sweden", flag: "🇸🇪", length: 9 },
    { code: "+41", country: "Switzerland", flag: "🇨🇭", length: 9 },
    { code: "+963", country: "Syria", flag: "🇸🇾", length: 9 },
    { code: "+992", country: "Tajikistan", flag: "🇹🇯", length: 9 },
    { code: "+255", country: "Tanzania", flag: "🇹🇿", length: 9 },
    { code: "+66", country: "Thailand", flag: "🇹🇭", length: 9 },
    { code: "+228", country: "Togo", flag: "🇹🇬", length: 8 },
    { code: "+216", country: "Tunisia", flag: "🇹🇳", length: 8 },
    { code: "+90", country: "Turkey", flag: "🇹🇷", length: 10 },
    { code: "+993", country: "Turkmenistan", flag: "🇹🇲", length: 8 },
    { code: "+256", country: "Uganda", flag: "🇺🇬", length: 9 },
    { code: "+380", country: "Ukraine", flag: "🇺🇦", length: 9 },
    { code: "+971", country: "United Arab Emirates", flag: "🇦🇪", length: 9 },
    { code: "+44", country: "United Kingdom", flag: "🇬🇧", length: 10 },
    { code: "+598", country: "Uruguay", flag: "🇺🇾", length: 8 },
    { code: "+998", country: "Uzbekistan", flag: "🇺🇿", length: 9 },
    { code: "+58", country: "Venezuela", flag: "🇻🇪", length: 10 },
    { code: "+84", country: "Vietnam", flag: "🇻🇳", length: 9 },
    { code: "+967", country: "Yemen", flag: "🇾🇪", length: 9 },
    { code: "+260", country: "Zambia", flag: "🇿🇲", length: 9 },
    { code: "+263", country: "Zimbabwe", flag: "🇿🇼", length: 9 },
];
